### ISSUE TITLE
[BUG] Databricks 11.3 Executor Broadcast throws exception when UCX shuffle is enabled

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/cudf-spark#7722]
**Describe the bug**
When enabling the RAPIDS Shuffle Manager with UCX mode, we get a ClassCastException:

```
...
Caused by: java.lang.ClassCastException: com.nvidia.spark.rapids.GpuColumnVectorFromBuffer cannot be cast to com.nvidia.spark.rapids.SerializedTableColumn
	at com.nvidia.spark.rapids.HostShuffleCoalesceIterator.$anonfun$bufferNextBatch$1(GpuShuffleCoalesceExec.scala:145)
	at com.nvidia.spark.rapids.HostShuffleCoalesceIterator.$anonfun$bufferNextBatch$1$adapted(GpuShuffleCoalesceExec.scala:140)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:87)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:85)
	at com.nvidia.spark.rapids.HostShuffleCoalesceIterator.closeOnExcept(GpuShuffleCoalesceExec.scala:80)
	at com.nvidia.spark.rapids.HostShuffleCoalesceIterator.bufferNextBatch(GpuShuffleCoalesceExec.scala:140)
	at com.nvidia.spark.rapids.HostShuffleCoalesceIterator.hasNext(GpuShuffleCoalesceExec.scala:163)
	at com.nvidia.spark.rapids.GpuShuffleCoalesceIterator.hasNext(GpuShuffleCoalesceExec.scala:200)
	at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:93)
	at org.apache.spark.sql.rapids.execution.GpuExecutorBroadcastHelper$.getExecutorBroadcastBatch(GpuExecutorBroadcastHelper.scala:94)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastHashJoinExec.$anonfun$getExecutorBuiltBatchAndStreamIter$1(GpuBroadcastHashJoinExec.scala:143)
...
```

**Steps/Code to reproduce bug**

Reproduce case using Scala Notebook:

```
spark.conf.set("spark.rapids.sql.enabled", true)
spark.conf.set("spark.sql.adaptive.enabled", true)
spark.conf.set("spark.sql.optimizer.dynamicPartitionPruning.enabled", true)
spark.conf.set("spark.databricks.delta.optimizeWrite.enabled", false)



import org.apache.spark.sql.functions.col


spark.range(1000).select(col("id"), col("id").as("k")).write.partitionBy("k").format("parquet").mode("overwrite").save("/navink/tmp/myfact")
spark.range(100).select(col("id"), col("id").as("k")).write.format("parquet").mode("overwrite").save("/navink/tmp/mydim")
spark.read.parquet("/navink/tmp/myfact").createOrReplaceTempView("fact")
spark.read.parquet("/navink/tmp/mydim").createOrReplaceTempView("dim")
val df = spark.sql("SELECT fact.id, fact.k FROM fact JOIN dim ON fact.k = dim.k AND dim.id < 2")
df.collect()

```

**Expected behavior**
The query should execute normally.

**Environment details (please complete the following information)**
 - Environment location: Databricks 11.3

**Additional context**
- See https://github.com/NVIDIA/spark-rapids/issues/7599 for cleanup related task for handling executor broadcast columnar batch
- Note the AQE edge case where an non-replaced CPU join must consume a reused GPU exchange. In that case, an extra CPU ShuffleExchangeExec is inserted for the Databricks join code to consume what it expects as an executor broadcast.
   - See https://github.com/NVIDIA/spark-rapids/blob/f1829eb327a5cf4afcaaf5609837ac05f655c4d6/sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/shims/SparkShims.scala#L89 and https://github.com/NVIDIA/spark-rapids/blob/f1829eb327a5cf4afcaaf5609837ac05f655c4d6/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala#L172

**Comment by sameerz** [comment]
We no longer support Databricks 11.3
